#[derive(Debug, PartialEq, Clone)]
pub enum Token {
    Bang,
    Comma,
    Dot,
    Minus,
    Plus,
    Semicolon,
    Slash,
    Star,
    Equal,
    Less,
    LessEqual,
    Greater,
    GreaterEqual,
    LeftParen,
    RightParen,
    LeftBrace,
    RightBrace,
    EqualEqual,
    BangEqual,
    Space,
    Tab,
    Newline,
    Comment,
    ReservedWord(String),
    StringLiterals(String),
    NumberLiterals(String),
    Identifier(String),
    UnexpectedToken(usize, char),
    UnterminatedString(usize),
}
